name: Deploy

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            eurico149/marketcrud-api:latest
            eurico149/marketcrud-api:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Push Front
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            eurico149/marketcrud-front:latest
            eurico149/marketcrud-front:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync infra
        run: |
          rsync -av --delete infra/ /home/$USER/MarketCRUD/

      - name: Deploy stack
        env:
          MARKETCRUD_MONGO_USERNAME: ${{ secrets.MARKETCRUD_MONGO_USERNAME }}
          MARKETCRUD_MONGO_PASSWORD: ${{ secrets.MARKETCRUD_MONGO_PASSWORD }}

          MARKETCRUD_URL_FRONTEND: ${{ vars.MARKETCRUD_URL_FRONTEND }}

          MARKETCRUD_MONGO_URI: mongodb://${{ secrets.MARKETCRUD_MONGO_USERNAME }}:${{ secrets.MARKETCRUD_MONGO_PASSWORD }}@mongo:27017/?authSource=admin
          MARKETCRUD_JWT_REFRESH_SECRET: ${{ secrets.MARKETCRUD_JWT_REFRESH_SECRET }}
          MARKETCRUD_JWT_ACCESS_SECRET: ${{ secrets.MARKETCRUD_JWT_ACCESS_SECRET }}
        run: |
          cd /home/$USER/MarketCRUD
          docker compose -f docker-compose.prod.yaml pull
          docker compose -f docker-compose.prod.yaml up -d --remove-orphans
